const tech_icons = [
  { name: 'adonisjs', icons: ['original', 'original-wordmark'] },
  { name: 'aftereffects', icons: ['original', 'plain'] },
  {
    name: 'amazonwebservices',
    short_name: 'aws',
    icons: ['original', 'original-wordmark', 'plain-wordmark'],
  },
  {
    name: 'android',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'aarch64', icons: ['original', 'plain'] },
  {
    name: 'angularjs',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'apache',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'apachekafka', icons: ['original', 'original-wordmark'] },
  {
    name: 'appcelerator',
    icons: ['original', 'original-wordmark', 'plain-wordmark'],
  },
  { name: 'apple', icons: ['original'] },
  {
    name: 'appwrite',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'arduino',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'atom', icons: ['original', 'original-wordmark'] },
  {
    name: 'azure',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'babel', icons: ['original', 'plain'] },
  {
    name: 'backbonejs',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'bash', icons: ['original', 'plain'] },
  {
    name: 'behance',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'bitbucket', icons: ['original', 'original-wordmark'] },
  { name: 'bootstrap', icons: ['original', 'plain', 'plain-wordmark'] },
  { name: 'bulma', icons: ['plain'] },
  {
    name: 'bower',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'c', icons: ['original', 'plain', 'line'] },
  {
    name: 'cakephp',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'canva', icons: ['original'] },
  {
    name: 'centos',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'ceylon',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'chrome',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'circleci', icons: ['plain', 'plain-wordmark'] },
  { name: 'clojure', icons: ['original', 'line'] },
  { name: 'clojurescript', icons: ['original', 'plain'] },
  { name: 'codecov', icons: ['plain'] },
  { name: 'codeigniter', icons: ['plain', 'plain-wordmark'] },
  { name: 'codepen', icons: ['plain', 'original-wordmark'] },
  { name: 'coffeescript', icons: ['original', 'original-wordmark'] },
  { name: 'composer', icons: ['original', 'line', 'line-wordmark'] },
  { name: 'confluence', icons: ['original', 'original-wordmark'] },
  {
    name: 'couchdb',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'cplusplus', icons: ['original', 'plain', 'line'] },
  { name: 'csharp', icons: ['original', 'plain', 'line'] },
  {
    name: 'css3',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'cucumber', icons: ['plain', 'plain-wordmark'] },
  { name: 'crystal', icons: ['original', 'original-wordmark'] },
  { name: 'd3js', icons: ['original', 'plain'] },
  {
    name: 'dart',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'debian',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'denojs', icons: ['original', 'original-wordmark'] },
  {
    name: 'devicon',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'django', icons: ['original', 'plain', 'line'] },
  {
    name: 'docker',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'doctrine',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  {
    name: 'dot-net',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'dotnetcore', icons: ['original', 'plain'] },
  {
    name: 'drupal',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'digitalocean',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'electron', icons: ['original', 'original-wordmark'] },
  { name: 'eleventy', icons: ['original', 'plain'] },
  {
    name: 'elixir',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'elm',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'ember', icons: ['original-wordmark'] },
  {
    name: 'embeddedc',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'erlang',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'express', icons: ['original', 'original-wordmark'] },
  { name: 'facebook', icons: ['original', 'plain'] },
  { name: 'feathersjs', icons: ['original'] },
  { name: 'figma', icons: ['original', 'plain'] },
  { name: 'filezilla', icons: ['plain', 'plain-wordmark'] },
  { name: 'firebase', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'firefox',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'flask', icons: ['original', 'original-wordmark'] },
  { name: 'flutter', icons: ['original', 'plain'] },
  {
    name: 'foundation',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'fsharp', icons: ['original', 'plain'] },
  { name: 'gatling', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'gatsby',
    icons: ['plain', 'original', 'original-wordmark', 'plain-wordmark'],
  },
  { name: 'gcc', icons: ['original', 'plain'] },
  {
    name: 'gimp',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'git',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'github', icons: ['original', 'original-wordmark'] },
  {
    name: 'gitlab',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'gitter', icons: ['plain', 'plain-wordmark'] },
  { name: 'go', icons: ['original', 'original-wordmark', 'plain', 'line'] },
  {
    name: 'google',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'googlecloud',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'gradle', icons: ['plain', 'plain-wordmark'] },
  { name: 'grails', icons: ['original', 'plain'] },
  { name: 'graphql', icons: ['plain', 'plain-wordmark'] },
  { name: 'groovy', icons: ['original', 'plain'] },
  {
    name: 'grunt',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'gulp', icons: ['plain'] },
  {
    name: 'godot',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'haskell',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'handlebars', icons: ['original', 'original-wordmark'] },
  { name: 'haxe', icons: ['original', 'plain'] },
  {
    name: 'heroku',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'html5',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'ie10', icons: ['original'] },
  { name: 'illustrator', icons: ['plain', 'line'] },
  {
    name: 'inkscape',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'intellij',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'ionic', icons: ['original', 'original-wordmark'] },
  {
    name: 'jamstack',
    icons: ['original', 'original-wordmark', 'plain-wordmark'],
  },
  { name: 'jasmine', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'java',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'javascript', icons: ['original', 'plain'] },
  {
    name: 'jeet',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'jest', icons: ['plain'] },
  { name: 'jenkins', icons: ['line', 'original', 'plain'] },
  { name: 'jetbrains', icons: ['original', 'plain'] },
  {
    name: 'jira',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'jquery',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'julia',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'jupyter',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'karma', icons: ['original', 'plain'] },
  {
    name: 'kotlin',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'knockout', icons: ['plain-wordmark'] },
  {
    name: 'krakenjs',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'kubernetes', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'labview',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'laravel', icons: ['plain', 'plain-wordmark'] },
  { name: 'less', icons: ['plain-wordmark'] },
  {
    name: 'linkedin',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'lua',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'linux', icons: ['original', 'plain'] },
  { name: 'materialui', icons: ['original', 'plain'] },
  { name: 'matlab', icons: ['original', 'plain', 'line'] },
  { name: 'magento', icons: ['original', 'original-wordmark', 'line'] },
  { name: 'markdown', icons: ['original'] },
  {
    name: 'meteor',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'minitab', icons: ['original', 'plain'] },
  { name: 'mocha', icons: ['plain'] },
  {
    name: 'modx',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'mongodb',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'moodle',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'msdos', icons: ['original', 'plain', 'line'] },
  {
    name: 'mysql',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'neo4j',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'nestjs', icons: ['plain', 'plain-wordmark'] },
  { name: 'nextjs', icons: ['original', 'line', 'original-wordmark'] },
  { name: 'nginx', icons: ['original'] },
  {
    name: 'nixos',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'nodejs',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'nodewebkit',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'npm', icons: ['original-wordmark'] },
  { name: 'numpy', icons: ['original', 'original-wordmark'] },
  {
    name: 'nuxtjs',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'objectivec', icons: ['plain'] },
  {
    name: 'opera',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'ocaml',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'opengl', icons: ['original', 'plain'] },
  { name: 'oracle', icons: ['original'] },
  { name: 'pandas', icons: ['original', 'original-wordmark'] },
  { name: 'perl', icons: ['original', 'plain'] },
  { name: 'phalcon', icons: ['original', 'plain'] },
  { name: 'photoshop', icons: ['plain', 'line'] },
  { name: 'php', icons: ['original', 'plain'] },
  {
    name: 'phpstorm',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'postgresql',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'premierepro', icons: ['plain', 'original'] },
  {
    name: 'processing',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'protractor', icons: ['plain', 'plain-wordmark'] },
  { name: 'putty', icons: ['original', 'plain'] },
  {
    name: 'pycharm',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'python',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'raspberrypi',
    icons: ['original', 'original-wordmark', 'line', 'line-wordmark'],
  },
  {
    name: 'phoenix',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'qt', icons: ['original'] },
  { name: 'r', icons: ['original', 'plain'] },
  { name: 'rails', icons: ['original-wordmark', 'plain', 'plain-wordmark'] },
  { name: 'react', icons: ['original', 'original-wordmark'] },
  {
    name: 'redhat',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'redis',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'redux', icons: ['original'] },
  { name: 'rocksdb', icons: ['plain'] },
  {
    name: 'ruby',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'rubymine',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'rust', icons: ['plain'] },
  {
    name: 'safari',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line-wordmark',
      'line',
    ],
  },
  { name: 'salesforce', icons: ['original', 'plain'] },
  { name: 'rstudio', icons: ['original', 'plain'] },
  { name: 'sass', icons: ['original'] },
  {
    name: 'scala',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'sequelize',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'shopware', icons: ['original', 'original-wordmark'] },
  {
    name: 'sketch',
    icons: ['original', 'original-wordmark', 'line', 'line-wordmark'],
  },
  {
    name: 'slack',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'socketio', icons: ['original', 'original-wordmark'] },
  { name: 'sourcetree', icons: ['original', 'original-wordmark'] },
  {
    name: 'spring',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'spss', icons: ['original', 'plain'] },
  { name: 'sqlalchemy', icons: ['original', 'original-wordmark', 'plain'] },
  { name: 'subversion', icons: ['original', 'original-wordmark'] },
  {
    name: 'microsoftsqlserver',
    short_name: 'sqlserver',
    icons: ['plain', 'plain-wordmark'],
  },
  { name: 'ssh', icons: ['original', 'original-wordmark'] },
  { name: 'stylus', icons: ['original'] },
  {
    name: 'svelte',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'swift',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'symfony', icons: ['original', 'original-wordmark'] },
  {
    name: 'storybook',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'tailwindcss', icons: ['original-wordmark', 'plain'] },
  {
    name: 'tensorflow',
    icons: ['original', 'original-wordmark', 'line', 'line-wordmark'],
  },
  { name: 'threejs', icons: ['original', 'original-wordmark'] },
  {
    name: 'tomcat',
    icons: ['original', 'original-wordmark', 'line', 'line-wordmark'],
  },
  { name: 'tortoisegit', icons: ['original', 'plain', 'line'] },
  {
    name: 'towergit',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'travis', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'thealgorithms',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'trello', icons: ['plain', 'plain-wordmark'] },
  { name: 'twitter', icons: ['original'] },
  { name: 'typescript', icons: ['original', 'plain'] },
  {
    name: 'typo3',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'ubuntu', icons: ['plain', 'plain-wordmark'] },
  { name: 'unity', icons: ['original', 'original-wordmark'] },
  { name: 'unix', icons: ['original'] },
  { name: 'uwsgi', icons: ['original', 'plain'] },
  {
    name: 'vagrant',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'vim', icons: ['original', 'plain'] },
  { name: 'visualstudio', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'vuejs',
    icons: [
      'original',
      'original-wordmark',
      'plain',
      'plain-wordmark',
      'line',
      'line-wordmark',
    ],
  },
  { name: 'vuestorefront', icons: ['original', 'plain'] },
  {
    name: 'vscode',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'weblate',
    icons: ['original', 'plain', 'original-wordmark', 'plain-wordmark'],
  },
  {
    name: 'webpack',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  {
    name: 'webstorm',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'windows8', icons: ['original', 'original-wordmark'] },
  {
    name: 'woocommerce',
    icons: ['original', 'plain', 'original-wordmark', 'plain-wordmark'],
  },
  { name: 'wordpress', icons: ['original', 'plain', 'plain-wordmark'] },
  { name: 'xd', icons: ['plain', 'line'] },
  { name: 'yarn', icons: ['original', 'original-wordmark'] },
  {
    name: 'yii',
    icons: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
  },
  { name: 'yunohost', icons: ['original', 'plain'] },
  { name: 'zend', icons: ['plain', 'plain-wordmark'] },
  {
    name: 'zig',
    icons: ['original', 'original-wordmark', 'plain-wordmark'],
  },
];

export { tech_icons };
