const themes = [
  { label: 'Default', value: 'default' },
  { label: 'Dark', value: 'dark' },
  { label: 'Radical', value: 'radical' },
  { label: 'Merko', value: 'merko' },
  { label: 'Gruvbox', value: 'gruvbox' },
  { label: 'Gruvbox Light', value: 'gruvbox_light' },
  { label: 'Tokyonight', value: 'tokyonight' },
  { label: 'Onedark', value: 'onedark' },
  { label: 'Cobalt', value: 'cobalt' },
  { label: 'Synthwave', value: 'synthwave' },
  { label: 'Highcontrast', value: 'highcontrast' },
  { label: 'Dracula', value: 'dracula' },
  { label: 'Prussian', value: 'prussian' },
  { label: 'Monokai', value: 'monokai' },
  { label: 'Vue', value: 'vue' },
  { label: 'Vue Dark', value: 'vue-dark' },
  { label: 'Shades Of Purple', value: 'shades-of-purple' },
  { label: 'Nightowl', value: 'nightowl' },
  { label: 'Buefy', value: 'buefy' },
  { label: 'Blue Green', value: 'blue-green' },
  { label: 'Algolia', value: 'algolia' },
  { label: 'Great Gatsby', value: 'great-gatsby' },
  { label: 'Darcula', value: 'darcula' },
  { label: 'Bear', value: 'bear' },
  { label: 'Solarized Dark', value: 'solarized-dark' },
  { label: 'Solarized Light', value: 'solarized-light' },
  { label: 'Chartreuse Dark', value: 'chartreuse-dark' },
  { label: 'Nord', value: 'nord' },
  { label: 'Gotham', value: 'gotham' },
  { label: 'Material Palenight', value: 'material-palenight' },
  { label: 'Graywhite', value: 'graywhite' },
  { label: 'Vision Friendly Dark', value: 'vision-friendly-dark' },
  { label: 'Ayu Mirage', value: 'ayu-mirage' },
  { label: 'Midnight Purple', value: 'midnight-purple' },
  { label: 'Calm', value: 'calm' },
  { label: 'Flag India', value: 'flag-india' },
  { label: 'Omni', value: 'omni' },
  { label: 'React', value: 'react' },
  { label: 'Jolly', value: 'jolly' },
  { label: 'Maroongold', value: 'maroongold' },
  { label: 'Yeblu', value: 'yeblu' },
  { label: 'Blueberry', value: 'blueberry' },

  // no working to medium posts

  { label: 'Slateorange', value: 'slateorange' },
  { label: 'Kacho Ga', value: 'kacho_ga' },
  { label: 'Outrun', value: 'outrun' },
  { label: 'Ocean Dark', value: 'ocean_dark' },
  { label: 'City Lights', value: 'city_lights' },
  { label: 'Github Dark', value: 'github_dark' },
  { label: 'Discord Old Blurple', value: 'discord_old_blurple' },
  { label: 'Aura Dark', value: 'aura_dark' },
  { label: 'Panda', value: 'panda' },
  { label: 'Noctis Minimus', value: 'noctis_minimus' },
  { label: 'Cobalt2', value: 'cobalt2' },
  { label: 'Swift', value: 'swift' },
  { label: 'Aura', value: 'aura' },
  { label: 'Apprentice', value: 'apprentice' },
  { label: 'Moltack', value: 'moltack' },
  { label: 'CodeSTACKr', value: 'codeSTACKr' },
  { label: 'Rose Pine', value: 'rose_pine' },
];

export { themes };
