name: ci
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.12.4
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting
        run: pnpm lint

      - name: Test
        run: pnpm test --coverage=false

      - name: Build
        run: pnpm build

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.12.4
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium

      - name: Run E2E tests
        run: pnpm test:e2e
